apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: nodejs-app-cluster
  region: us-east-1
  version: "1.28"
vpc:
  subnets:
    public:
      us-east-1a: { id: subnet-0f4899f56381ef714 }
      us-east-1b: { id: subnet-0749a9be8604918bf }
nodeGroups:
  - name: ng-public
    instanceType: t3.medium  # Cheapest general-purpose
    desiredCapacity: 1
    minSize: 1
    maxSize: 2
    volumeSize: 20  # GB
    ssh:
      allow: true
      publicKeyName: gb_key
    iam:
      attachPolicyARNs:
        - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
