# charts/node-app/values.yaml
replicaCount: 1

image:
  repository: kelomo2502/node-k8s-app
  tag: v2
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 3000

mongodb:
  uri: "mongodb+srv://kelvinoye:Myrrhh%402502@cluster0.xjntp.mongodb.net/argoCd-app?retryWrites=true&w=majority&appName=Cluster0"

resources: {}
ingress:
  enabled: false  # Set to true if you want ingress
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
