# helm/node-app/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "node-app.fullname" . }}-db-secret
type: Opaque
stringData:
  mongo-uri: {{ .Files.Get "secrets/.env" | trim }}